import com.github.calcacuervo.models.Reminder;
import com.github.calcacuervo.models.ReminderMessages;
import com.github.calcacuervo.models.Customer;

rule "Send Reminder to Customer every day"
    timer (cron:0 0 * * * ?)
when
	c: Customer ( suscriptionPaymentDone == false )
then
	insert (new Reminder(ReminderMessages.PAYMENT_NOT_DONE.getMessage()));
end

rule "Print message"
when
	r: Reminder ( )
then
	System.out.println(r.getMessage());
end

query "get reminders" 
    reminder : Reminder()
end