import com.gibhub.calcacuervo.timer.Reminder;
import com.gibhub.calcacuervo.timer.ReminderMessages;
import com.gibhub.calcacuervo.timer.Customer;
import com.gibhub.calcacuervo.timer.TimerSettings;

rule "Send Reminder to Customer every minute with 30 second delay"
    timer( expr: $d, $p; repeat-limit=5 )
when
    TimerSettings( $d : delay, $p : period )
	c: Customer ( suscriptionPaymentDone == false )
then
	insert (new Reminder(ReminderMessages.PAYMENT_NOT_DONE.getMessage()));
end

rule "Print message"
when
	r: Reminder ( )
then
	System.out.println(r.getMessage());
end

query "get reminders" 
    reminder : Reminder()
end